# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 879166e7d168f7a74adaab0027246f2326368fd7237ef42dd02780eed59aa9e971280217a616de4bde7c4defdc72a29dc326efd67f3144a33321d239d330669a

test:
  secret_key_base: a2075b4ff690afe0d1d2598d35d05c049d5338737d8d2238c6f8c6ba42779e3378afaf176789d385db20311a7a79f44d5d87329948dbb981055e161a207de3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
